import React from 'react';
import Navbar from './Navbar';
import Footer from './Footer';
import Head from 'next/head';
import '@fontsource/poppins';
import '@fontsource/poppins/200.css';
import '@fontsource/poppins/400.css';
import '@fontsource/poppins/600.css';
import '@fontsource/poppins/900.css';

function Layout({ children }) {
	return (
		<>
			<Head>
				<title>Carli&apos;s Auto Spa | Pennsylvania</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<main>{children}</main>
			<Footer />
		</>
	);
}

export default Layout;
